
spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: johnson
    password: johnson.123
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081